### ISSUE TITLE
ENVI-Met2dPlant: 2D trees probable issue

### ISSUE THREAD

**Issue by frank984** [AntonelloDN/lb_envimet#3]
Hi @AntonelloDN 
I have tryed to model some trees in a urban area with your ENVI-Met2dPlant component using this example:
![image](https://user-images.githubusercontent.com/6491927/47015710-f5b88e00-d14d-11e8-903d-de6227b04dab.png)
The result is that the T1  input (Tree very dense 10 m) is not considered: it is considered a "XX" area with grass 50 cm aver. dense:
![image](https://user-images.githubusercontent.com/6491927/47015973-b9d1f880-d14e-11e8-8cf8-46d272088063.png)
Could you explain me how can I solve without considering 3D Plants?

**Comment by AntonelloDN** [comment]
Hi @frank984,

Here is how to manage multiple input:
![image](https://user-images.githubusercontent.com/16763953/47041523-52856a00-d189-11e8-9fa4-16bd7ca693f9.png)
The length of geometry list has to be equal to the legth of material list.

Let me know if it works,

Antonello

**Comment by frank984** [comment]
Thank you for the suggestion. Now it work properly.
Regards,
Francesco
